logdata:
  extends:
    file: ../docker-compose-commons.yml
    service: logdata
   
entry:
  extends:
    file: ../docker-compose-commons.yml
    service: entry
  volumes:
    - ./boot-scripts/02-marmotta-backend.js:/etc/fusepool-p3/boot-scripts/02-marmotta-backend.js
   
marmotta:
  image: fusepoolp3/ldp-marmotta
  restart: unless-stopped
   
core:
  extends:
    file: ../docker-compose-commons.yml
    service: core
  links:
   - elk
   - marmotta:ldp
  volumes_from:
   - logdata
  environment:
   - LDPURI=http://ldp:8080/
    
stanbol:
  extends:
    file: ../docker-compose-commons.yml
    service: stanbol
   
batchrefine:
  extends:
    file: ../docker-compose-commons.yml
    service: batchrefine
  volumes_from:
    - logdata
    
openrefine:
  extends:
    file: ../docker-compose-commons.yml
    service: openrefine
  volumes_from:
    - logdata
    
elk:
  extends:
    file: ../docker-compose-commons.yml
    service: elk

pundittransformer:
  extends:
    file: ../docker-compose-commons.yml
    service: pundittransformer
  environment:
   - LDPURI=http://ldp:8080/
  links:
    - core
    - marmotta:ldp
    - entry